### ISSUE TITLE
Activity Entity Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#78]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] In the entity diagram, the CA "enforces" the scheme. Elsewhere it sponsors it - the definition needs to be consistent.
- [x] There is an activity type declared in the diagram but no definition, have we defined this anywhere?
- [x] Some of the relationships are dotted lines, what is the significance of this?
- [x] The diagram says activities are "applied to" establishments but I don't think this is the correct term.
- [x] Missing link to the enrolment entity - we need to define one in the next pass.
- [ ] Need to develop a code list pattern.
- [x] Representation of cardinality of relationships is inconsistent across models - need to decide and tidy up.

**Comment by JDSFSA** [comment]
1 Can language change in relation to contex of the interaction? FOr example LA's carry our Inspections and Enforcement action on meatplants but approval to open a meatplant or change activities permitted within an establishment is restricted to the FSA.
2 Activity type is being removed (entity was deleted)
3 dotted lines removed, no relevance
4 Change language to Activity "Approved For" but I'm not sure on that either possibly "Granted" or "Applied to".
5 Missing link due to entity being in drafts
6
7 De-cluttered the diagram removing entities that aren't required for Activity.
